# Generated by Django 5.1.1 on 2024-10-22 07:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=datetime.date(1994, 1, 1), verbose_name='Birthday')),
                ('ethnicity', models.CharField(blank=True, choices=[('Asian', 'Asian or Asian British'), ('Black', 'Black, Black British, Caribbean or African'), ('Mixed', 'Mixed or multiple ethnic groups'), ('White', 'White'), ('Other', 'Other ethnic group')], max_length=50, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisations.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
