# Generated by Django 5.1.1 on 2024-10-20 22:00
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),  # Update this to reflect your initial migration
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True, blank=True),
        ),
    ]