# Generated by Django 5.1.1 on 2024-10-20 21:19
from django.db import migrations
from datetime import date

def set_default_dob(apps, schema_editor):
    # Get the UserProfile model
    UserProfile = apps.get_model('register', 'UserProfile')
    # Update records where date_of_birth is NULL, setting it to the default date
    UserProfile.objects.filter(date_of_birth__isnull=True).update(date_of_birth=date(1994, 1, 1))

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),  # Replace with your actual migration file name
    ]

    operations = [
        migrations.RunPython(set_default_dob),
    ]