# Generated by Django 5.1.1 on 2024-10-20 22:00
from django.db import migrations
from datetime import date

def set_default_eth(apps, schema_editor):
    # Get the UserProfile model
    UserProfile = apps.get_model('register', 'UserProfile')
    # Update records where date_of_birth is NULL, setting it to the default date
    UserProfile.objects.filter(ethnicity__isnull=True).update(ethnicity='asian')

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_date_of_birth'),  # Replace with your actual migration file name
    ]

    operations = [
        migrations.RunPython(set_default_eth),
    ]