# Generated by Django 5.1.1 on 2024-10-20 22:05
import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_set_default_dob'),  # Ensure it points to the previous migration
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[
                ('asian', 'Asian or Asian British'),
                ('black', 'Black, Black British, Caribbean or African'),
                ('mixed', 'Mixed or multiple ethnic groups'),
                ('white', 'White'),
                ('other', 'Other ethnic group')
            ], max_length=50, null=True),
        ),
    ]