# Generated by Django 5.1.1 on 2024-10-20 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20241020_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1994, 1, 1), verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian or Asian British'), ('black', 'Black, Black British, Caribbean or African'), ('mixed', 'Mixed or multiple ethnic groups'), ('white', 'White'), ('other', 'Other ethnic group')], max_length=50, null=True),
        ),
    ]
