# Generated by Django 5.1.1 on 2024-10-20 22:05
# Generated by Django 5.1.1 on 2024-10-20 22:00

from django.db import migrations

def set_default_eth(apps, schema_editor):
    UserProfile = apps.get_model('register', 'UserProfile')
    UserProfile.objects.filter(ethnicity__isnull=True).update(ethnicity='asian')

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userprofile_ethnicity'),  # Ensure it points to the previous migration
    ]

    operations = [
        migrations.RunPython(set_default_eth),
    ]