# Generated by Django 5.1.1 on 2024-10-21 20:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_set_default_eth'),  # Ensure it points to the previous migration
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[
                ('Asian', 'Asian or Asian British'),
                ('Black', 'Black, Black British, Caribbean or African'),
                ('Mixed', 'Mixed or multiple ethnic groups'),
                ('White', 'White'),
                ('Other', 'Other ethnic group')
            ], max_length=50, null=True),
        ),
    ]