# Generated by Django 5.1.1 on 2024-10-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_userprofile_date_of_birth_userprofile_ethnicity'),
    ]

    operations = [
    ]
