# Generated by Django 5.1.1 on 2024-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='sentiment',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='subjectivity',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=18, null=True),
        ),
    ]
