# Generated by Django 5.1.1 on 2024-10-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0002_userprofile'),
        ('polls', '0004_choice_manifesto_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisations.organisation'),
        ),
    ]
