# Generated by Django 5.1.1 on 2024-10-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
