# Generated by Django 5.1.1 on 2024-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='password',
            field=models.CharField(default='temporary_default_password', max_length=128),
        ),
    ]
